### ISSUE TITLE
Не могу запустить проект локально

### ISSUE THREAD

**Issue by ubaidisaev** [CSSSR/csssr.blog#387]
Проблемы с установкой пакета `@csssr/csssr.image`
Можно ссылку на данный пакет.

**Comment by ArtyomResh** [comment]
Привет! :) 

Репа и сам пакет `@csssr/csssr.image` пока находятся в закрытом доступе. Нам нужно дописать для него доку и проверить на наличие открытых секретов. Мы постараемся это сделать как можно быстрее и опубликовать его в открытый доступ.

**Comment by ubaidisaev** [comment]
@ArtyomResh  Привет. Ясно )
